name: MVN build with mirrors

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: ['3.8.2' ]

    name: Maven ${{ matrix.maven }} sample

    steps:
      - uses: actions/checkout@v2
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v3.8.2
        with:
          java-version: 1.8.0.212
          maven-version: ${{ matrix.maven }}
          mirrors: '[{"id": "digi-repo", "name": "digi-repo", "mirrorOf": "rxtx, rxtx-native", "url": "http://ftp1.digi.com/support/m-repo/"}]'

      - run: mvn clean compile assembly:single